### ISSUE TITLE
Readiness for release?

### ISSUE THREAD

**Issue by jtdaugherty** [chhackett/vty-windows#6]
Greetings!

In connection with https://github.com/jtdaugherty/vty/issues/260, I'd love to understand what remains to be done on `vty-windows` before it's ready for release. I'd like the next release of Vty to happen in coordination with this package's release, and right now I don't know how close this is to being ready.

**Comment by chhackett** [comment]
Hey Jonathan,
So sorry I haven't communicated much lately. I was busy with life stuff...

But I have been trying to prepare for release, and during testing I discovered a serious problem with vty-windows.
Rendering of unicode characters (outside range of ASCII) does not work correctly at the moment. For example, here is the output of the brick-border-demo:
|               |Γöé                 ΓöéΓöâ
|               |Γöé                 ΓöéΓöâ
|  ascii style  |Γöé  unicode style  ΓöéΓöâ  unicode bold style|               |Γöé                 ΓöéΓöâ
|               |Γöé                 ΓöéΓöâ
+---------------+ΓööΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓ

I think I know the problem (Windows defaults to UTF-16 encoding). I just need to take a little time to find the way to set windows console to UTF-8, and finish testing. I will work on it this weekend.

If that turns out to be the only problem, then I would be willing to release as soon as I fix this issue.

**Comment by jtdaugherty** [comment]
Okay, no hurry! I had also been very busy with other things for a while until I had some time to work more on the vty release prep last week. That made me wonder where this package was at as well. To ensure that the releases are coordinated, how about you just let me know when things are starting to look good, and then we can both jointly pick a release date? That will also be important for me so I can plan on posting a public announcement or two in tandem with the releases.

**Comment by ShrykeWindgrace** [comment]
> Hey Jonathan, So sorry I haven't communicated much lately. I was busy with life stuff...
> 
> But I have been trying to prepare for release, and during testing I discovered a serious problem with vty-windows. Rendering of unicode characters (outside range of ASCII) does not work correctly at the moment. For example, here is the output of the brick-border-demo: | |Γöé ΓöéΓöâ | |Γöé ΓöéΓöâ | ascii style |Γöé unicode style ΓöéΓöâ unicode bold style| |Γöé ΓöéΓöâ | |Γöé ΓöéΓöâ +---------------+ΓööΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓ
> 
> I think I know the problem (Windows defaults to UTF-16 encoding). I just need to take a little time to find the way to set windows console to UTF-8, and finish testing. I will work on it this weekend.
> 
> If that turns out to be the only problem, then I would be willing to release as soon as I fix this issue.

I'd wager a bet that `getConsoleOutputCP`, `setConsoleOutputCP` and their friends from Win32 are the way to go. In most circumstances `65001` is equivalent to unicode. I'll try to take a look at that demo, too, but no promises before Monday.

**Comment by chhackett** [comment]
Thanks @ShrykeWindgrace, that did the trick. 

I also ran through all the other brick demos and didn't find any problems.
