### ISSUE TITLE
Relax base bounds?

### ISSUE THREAD

**Issue by jtdaugherty** [chhackett/vty-windows#7]
`vty` and `vty-unix` use `base >= 4.8 && < 5`. Any chance `vty-windows` could as well?

**Comment by chhackett** [comment]
@jtdaugherty @ShrykeWindgrace 
You know, since we're using a Win32 API call to extract input events, we probably can. I specified 4.17.1 when I reasoned that we needed the 'uncooked input on Windows' fix that was made in GHC 9.4.6. But we're not using standard IO anyway.
I will do some testing this week to verify, and hopefully change the base bounds by this weekend.

**Comment by jtdaugherty** [comment]
Okay, great!

**Comment by chhackett** [comment]
@jtdaugherty 
I did some testing, and I believe the earliest version of base we can support is 4.9. That is based on my understanding that the base version corresponds to a specific version of ghc. In our libraries vty-unix and vty-windows we use the StrictData extension, which wasn't introduced until 8.0.1 of ghc, or base 4.9.0.0.

So I've relaxed the version bounds of base back to 4.9.

**Comment by jtdaugherty** [comment]
Okay, thanks! 4.9 is GHC 8.0.1, which seems to me to be a good earliest version of GHC to support.
